# Generated by Django 3.1.1 on 2020-09-14 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('Content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/diaryImg')),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('font', models.IntegerField(default=1)),
                ('emotion', models.IntegerField(default=1)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
