# Generated by Django 3.1.1 on 2020-09-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='User',
            new_name='user',
        ),
    ]
